apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: llmops
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
